### ISSUE TITLE
The use case scenarios have a mix of tabs and spaces

### ISSUE THREAD

**Issue by TakenouchiTR** [JACorley1/UWG-SE2-Spring22-Team1#51]
The use case scenarios have an odd mix of tabs and spaces which does not clearly convey the intended nesting. Be sure to double check your use of whitespace in txt files (especially when using code editors which may render tabs differently or auto-switch between tabs and spaces).

An easy fix would be to use VSCode, select the search option on the left side, then replace `\t` with some number of spaces in only `.txt` files. Afterward, manually check each file to ensure that the tabbing is consistent.

**Comment by Steven-Carriger** [comment]
issue is resolved with commit e8d5230 and 
61d39c1 in update-usecases
