### ISSUE TITLE
HabitViewModel::determineFrequency will return the shortest frequency between the add and remove options

### ISSUE THREAD

**Issue by TakenouchiTR** [JACorley1/UWG-SE2-Spring22-Team1#78]
HabitViewModel::determineFrequency **MUST** be changed, otherwise the application **will not** work properly.

At the moment, it is grabbing the whichever frequency is the shortest between the add and remove/modify windows. Since I cannot access the remove/modify window until I add a habit, the first habit will _always_ be daily.

The method should be split into two methods, one for each window. It _will not work_ if it is kept this way.

**Comment by Steven-Carriger** [comment]
commit 9a644c5cf resolves this issue.
