### ISSUE TITLE
HabitViewModel's second constructor is an incorrect usage for a constructor.

### ISSUE THREAD

**Issue by TakenouchiTR** [JACorley1/UWG-SE2-Spring22-Team1#81]
The second constructor for HabitViewModel is an inappropriate usage of a constructor.
If we want control over which ServerCommunicator gets used, a constructor should be made where a server communicator is passed in as an argument.
We also shouldn't have so much repeated code between constructors. Use constructor chaining so that all of the default values are set in one location.

**Comment by Steven-Carriger** [comment]
Commit: 0c564a0 resolves this issue.
